apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-api
  template:
    metadata:
      labels:
        app: recipes-api
    spec:
      containers:
      - name: recipes-api
        image: tastycook.azurecr.io/recipes-api:v0.1.1
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recipes-api
spec:
  selector:
    app: recipes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
  type: NodePort