apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: default
  selector:
    matchLabels:
      name: recipes-api-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipes-api-pv
  labels:
    name: recipes-api-pv
spec:
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /var/lib/rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-api
  template:
    metadata:
      labels:
        app: recipes-api
    spec:
      containers:
      - name: recipes-api
        image: tastycook.azurecr.io/recipes-api:1685825790
        ports:
          - containerPort: 80
      - name: rabbitmq
        image: rabbitmq:management
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: recipes-api-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: recipes-api
spec:
  selector:
    app: recipes-api
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipes-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: recipes-api
                port:
                  number: 80
            path: /recipes(/|$)(.*)