apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: default
  selector:
    matchLabels:
      name: users-api-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-api-pv
  labels:
    name: users-api-pv
spec:
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /var/lib/rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: tastycook.azurecr.io/users-api:v0.1.1
          ports:
            - containerPort: 80
        - name: rabbitmq
          image: rabbitmq:management
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: users-api-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: users-api
                port:
                  number: 80
            path: /users(/|$)(.*)