apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-api
  template:
    metadata:
      labels:
        app: recipes-api
    spec:
      revisionHistoryLimit: 2
      containers:
        - name: recipes-api
          image: tastycook.azurecr.io/recipes-api:392cb37
          ports:
            - containerPort: 80
