apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipes-api-pv
  labels:
    name: recipes-api-pv
spec:
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /var/lib/rabbitmq