apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: products-api
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: products-api
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "products-api"
        maxAllowed:
          cpu: 400m
          memory: 800Mi
        controlledResources: ["cpu", "memory"]
