apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: users-api
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: users-api
  resourcePolicy:
    containerPolicies:
      - containerName: "recipes-api"
        maxAllowed:
          cpu: 400m
          memory: 800Mi
        controlledResources: ["cpu", "memory"]
