apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: default
  selector:
    matchLabels:
      name: rabbitmq-pv
