apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: rabbitmq
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: rabbitmq
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "rabbitmq"
        maxAllowed:
          cpu: 600m
          memory: 1Gi
        controlledResources: ["cpu", "memory"]
